### ISSUE TITLE
Nullifiers and Preventifiers optimization

### ISSUE THREAD

**Issue by davidp94** [EYBlockchain/ZKPChallenge#1]
I wanted to know why you are looping around the `ns` and `ds` arrays instead of storing a `bool` in a `mapping` that would mark them as spent ?

```
    for (uint i=0; i<nCount; i++) { //check this is an unspent commitment
      require(ns[i]!=n);
    }
    ns[nCount++] = n; //remember we spent it
    zs[zCount++] = z; //add Bob's token to the list of tokens
```

Could change to 

```
// definition
mapping(bytes8 => bool) private nsMapping;

// (...)

    // removed
    // for (uint i=0; i<nCount; i++) { //check this is an unspent commitment
    //   require(ns[i]!=n);
    // }
    require(!nsMapping[n]);
    ns[nCount++] = n; //remember we spent it
    nsMapping[n] = true;
```

**Comment by Westlad** [comment]
Good thought - Thanks!

**Comment by davidp94** [comment]
You can check 
https://github.com/barryWhiteHat/miximus/blob/master/contracts/MerkelTree.sol
https://github.com/barryWhiteHat/miximus/blob/master/contracts/Miximus.sol
To have a merkle tree of depth 29 ( 536870912 leaves )

**Comment by Westlad** [comment]
Thanks, in fact our Merkel tried is parameterized so we can change to a deeper one but we decided to stay shallow for this demo to minimise the compute overhead. We're very keen to optimise the code though (because it needs to get much faster/cheaper) so I really appreciate your suggestions.
