### ISSUE TITLE
License is incompatible with Open-Source

### ISSUE THREAD

**Issue by HarryR** [EYBlockchain/ZKPChallenge#2]
As per the terms of https://raw.githubusercontent.com/EYBlockchain/ZKPChallenge/master/LICENSE.txt

It seems that this license is broadly incompatible with 'open-source', and the 'Patent Pending' notice plastered everywhere is very ominous.

Do you have any plans to cooperate with the open-source community using a peer reviewed license with well understood terms and limitations?

**Comment by Westlad** [comment]
Yes, we're working on full open source. It's a regulatory issue. As EY is an audit firm we have to meet very strict rules about being independent from organisations we audit.  This extends to them not using software that we have written. We're working through with our legal team if this applies to open source or not. Hopefully we'll be through that soon.

**Comment by HarryR** [comment]
That's a shame, as I need to stay clear of projects with licensing terms such as these and more importantly the possibility of lawyers who aggressively pursue perceived intellectual property rights, lest my brain be somehow corrupted by EY's proprietary technology and it seeps into my own projects or those that I contribute to (regardless of who thought of it first).
